# Game chast config
# Percentage chance a given slot is filled with an item
slot-chance: 25

# Percentage chance a higher tiered item is chosen
lvlup-chance: 30

# The following allows you to change the default chest loot for the current game
# --------------------------------------------------------------------------
# The following format MUST be followed... or else the server WILL NOT start
#
# You may as many lvlup tags as you want below the items tag
#
# - ITEM_NAME;min_amount;max_amount;extra_data;enchantmen_ID;enchantment_lvl
# ITEM_NAME = The Bukkit valid name of the item.  Find a list here: http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html
# min_amount = The minimum number of this that can be chosen for a slot, should never be 0 or a negitive.
# max_amount = The maxium number of this that can be chosen for a slot, should never be 0 or a negitive.
# extra_data = [!NOT OPTIONAL!] Usually 0 in most cases, but for potions, use the potion DV, found here http://minecraft.gamepedia.com/Potion.  Also used for durabality, wool color, dye color, gold apple type, etc...
# enchantmen_ID = [OPTIONAL] The ID of the enchantment to be applied to the item.  The list of enchantment IDs can be found here: http://minecraft.gamepedia.com/Enchanting.  Do not attempt to add enchantments to potions -_-
# enchantment_lvl = [OPTIONAL] The level of the enchantment to be applied.  If left null and an enchantment is applied, level will default to one.

items:
    1:
    - SNOW_BALL;4;8;0
    - EGG;4;8;0
    - LEATHER_BOOTS;1;1;0
    - LEATHER_CHESTPLATE;1;1;0
    - LEATHER_HELMET;1;1;0
    - LEATHER_LEGGINGS;1;1;0
    - WOOD_SWORD;1;1;0
    - WOOD_AXE;1;1;0
    - WOOD_PICKAXE;1;1;0
    - WOOD;10;20;0
    - STONE;8;16;0
    - COOKED_BEEF;2;8;0
    - GRILLED_PORK;3;9;0
    - COOKIE;1;10;0
    - FISHING_ROD;1;1;0
    - WATER_BUCKET;1;1;0
    - LAVA_BUCKET;1;1;0
    - TNT;1;5;0
    - FLINT_AND_STEEL;1;1;0
    - COBBLESTONE;7;14;0
    - SANDSTONE;6;12;0
    2:
    - GOLD_SWORD;1;1;0
    - CHAINMAIL_CHESTPLATE;1;1;0
    - CHAINMAIL_BOOTS;1;1;0
    - IRON_LEGGINGS;1;1;0
    - IRON_HELMET;1;1;0
    - IRON_AXE;1;1;0
    - SNOW_BALL;8;16;0
    - EGG;8;16;0
    - IRON_HELMET;1;1;0;0;1
    - DIAMOND_PICKAXE;1;1;0
    - INK_SACK;1;1;0;19;1
    - IRON_AXE;1;1;0
    - GOLDEN_APPLE;1;2;0
    - DIAMOND_SPADE;1;1;0
    - STONE;8;16;0
    - WOOD;10;20;0
    - SANDSTONE;6;12;0
    - REDSTONE_BLOCK;9;18;0
    - PUMPKIN_PIE;1;4;0
    - WATER_BUCKET;1;1;0
    - LAVA_BUCKET;1;1;0
    3:
    - STONE_SWORD;1;1;0
    - ENDER_PEARL;1;3;0
    - SNOW_BALL;16;32;0
    - EGG;16;32;0
    - DIAMOND_CHESTPLATE;1;1;0
    - DIAMOND_BOOTS;1;1;0
    - GOLD_LEGGINGS;1;1;0;0;2
    - GOLD_HELMET;1;1;0;0;1
    - IRON_SWORD;1;1;0
    - GOLDEN_APPLE;2;3;0
    - REDSTONE_BLOCK;9;18;0
    - MOSSY_COBBLESTONE;12;24;0
    - NETHER_BRICK;6;12;0
    4:
    - IRON_SWORD;1;1;0;16;1
    - ENDER_PEARL;2;4;0
    - STONE_AXE;1;1;0;16;2
    - SNOW_BALL;32;64;0
    - EGG;32;64;0
    - DIAMOND_LEGGINGS;1;1;0
    - DIAMOND_HELMET;1;1;0
    - DIAMOND_AXE;1;1;0
    - MOSSY_COBBLESTONE;12;24;0
    5:
    - DIAMOND_SWORD;1;1;0
    - LEASH;1;1;0;19;5
    - DIAMOND;1;1;0;16;5
    - ENDER_PEARL;12;16;0
    - GOLDEN_APPLE;1;1;1
    - NETHERRACK;20;40;0
    - OBSIDIAN;15;30;0
